In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df["email"]    # Acessando a coluna email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [6]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [7]:
# Define o índice para a coluna email e modifica o DataFrame original
df.set_index("email", inplace=True)
# o inplace=True é necessário para modificar o DataFrame original, caso contrário,
# ele retornaria um novo DataFrame com o índice definido, mas não modificaria o DataFrame original.

In [8]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [9]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='str', name='email')

In [10]:
df.loc["CoreyMSchafer@gmail.com", "last"] # Acessando o valor da coluna last para o índice "CoreyMSchafer@gmail.com"

'Schafer'

In [11]:
df.iloc[1] # Acessando a segunda linha do DataFrame usando iloc, que é baseado em posição.

first    Jane
last      Doe
Name: JaneDoe@email.com, dtype: str

In [12]:
df.loc["JaneDoe@email.com"] # Acessando a linha correspondente ao índice "JaneDoe@email.com"

first    Jane
last      Doe
Name: JaneDoe@email.com, dtype: str

In [13]:
df.reset_index(inplace=True)    # Reseta o índice para o padrão numérico e modifica o DataFrame original
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe