In [31]:
# As chaves são as colunas e os valores são as linhas, ou seja, os dados de cada pessoa.

people = {
    "first": ["Corey", 'Jane', 'John','Adão'],
    "last": ["Schafer", 'Doe', 'Doe','Silva'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com','AdaoSilva@email.com']
}

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame(people)

In [34]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adão    Silva      AdaoSilva@email.com

In [35]:
df.sort_values(by='last') # Ordena o DataFrame com base na coluna 'last' (sobrenome) em ordem alfabética.

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adão    Silva      AdaoSilva@email.com

In [36]:
df.sort_values(by='last', ascending=False) # Ordena o DataFrame com base na coluna 'last' (sobrenome) em ordem alfabética decrescente.

   first     last                    email
3   Adão    Silva      AdaoSilva@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [37]:
df.sort_values(by=['last', 'first']) # Ordena o DataFrame primeiro pela coluna 'last' e, em caso de empate, pela coluna 'first'.
# Exemplo: Se houver duas pessoas com o mesmo sobrenome, elas serão ordenadas pelo nome.

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adão    Silva      AdaoSilva@email.com

In [ ]:
df.sort_values(by=['last', 'first'], ascending=[False, True])
# Ordena o DataFrame primeiro pela coluna 'last' em ordem alfabética decrescente e, em caso de empate, pela coluna 'first' em ordem alfabética crescente.

   first     last                    email
3   Adão    Silva      AdaoSilva@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [39]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adão    Silva      AdaoSilva@email.com

In [41]:
df['last'].sort_values() # Ordena apenas a coluna 'last' em ordem alfabética, retornando uma Series ordenada.

1        Doe
2        Doe
0    Schafer
3      Silva
Name: last, dtype: str