In [231]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [232]:
import pandas as pd

In [233]:
df = pd.DataFrame(people)

In [234]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [235]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [236]:
df.columns = ['first_name','last_name', 'email']

In [237]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [238]:
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [239]:
df.columns = df.columns.str.replace('_',' ')
df

  FIRST NAME LAST NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [240]:
df.columns = df.columns.str.replace(' ','_')
df.columns = [x.lower() for x in df.columns] # Converte os nomes das colunas para letras minúsculas usando uma list comprehension.

In [241]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [242]:
df.rename(columns={'first_name':'first', 'last_name': 'last'}, inplace = True)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [243]:
df.loc[2] = ['John','Smith','JhonSmith@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JhonSmith@email.com

In [244]:
df.loc[2, ['last','email']]

last                   Smith
email    JhonSmith@email.com
Name: 2, dtype: str

In [245]:
df.loc[2, ['last','email']] = ['Matheus', 'Matheus@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [246]:
df.loc[2,'last'] = 'Carlos'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Carlos        Matheus@email.com

In [247]:

# Usando o método at para atualizar um valor específico
# O método at é mais rápido do que loc para acessar um único valor, pois é otimizado para esse tipo de operação.
df.at[2,'last'] = 'Matheus'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [248]:
filtro = (df['email'] == 'JaneDoe@email.com')
df.loc[filtro, 'last'] = 'Smith'
df

# É necessário usar o método loc para atualizar os valores
# pois ele permite acessar e modificar os valores de forma eficiente, especialmente quando se trata de condições ou filtros.
# O método at é mais adequado para acessar um único valor específico.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane    Smith        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [249]:
filtro = (df['email'] == 'JaneDoe@email.com')
df.loc[filtro, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane    Smith        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [250]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          Matheus@email.com
Name: email, dtype: str

In [251]:
df['email'].str.upper()

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          MATHEUS@EMAIL.COM
Name: email, dtype: str

In [252]:
df['email'] = df['email'].str.upper()

# Pode ser usado o método str.lower() para converter os valores da coluna 'email' para letras minúsculas.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [253]:
df['email'].apply(len) # Aplica a função len a cada valor da coluna 'email', retornando o comprimento de cada string de email.

0    23
1    17
2    17
Name: email, dtype: int64

In [254]:
def update_email(email):
    return email.upper()  # ou email.upper() para converter para maiúsculas

In [255]:
df['email'].apply(update_email) # Aplica a função update_email a cada valor da coluna 'email', convertendo os emails para letras maiúsculas.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [256]:
df['email'] = df['email'].apply(update_email) # Atualiza a coluna 'email' com os valores convertidos para letras minúsculas usando a função update_email.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [257]:
df.apply(len, axis = 'columns') # Aplica a função len a cada linha do DataFrame, retornando o número de colunas em cada linha.
df.apply(len, axis='rows') # Aplica a função len a cada coluna do DataFrame, retornando o número de linhas em cada coluna.

first    3
last     3
email    3
dtype: int64

In [258]:
len(df.columns)

3

In [259]:
df.apply(pd.Series.min) # Aplica a função min a cada coluna do DataFrame, retornando o valor mínimo de cada coluna.
# Verifica o valor mínimo de cada coluna, o que pode ser útil para identificar o valor mais baixo em colunas numéricas ou a string mais "pequena" em colunas de texto.

first                      Corey
last                     Matheus
email    COREYMSCHAFER@GMAIL.COM
dtype: str

Usando a função applymap

In [260]:
df.applymap(len)

AttributeError: 'DataFrame' object has no attribute 'applymap'