In [15]:
# As chaves são as colunas e os valores são as linhas, ou seja, os dados de cada pessoa.

people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(people)

In [18]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [19]:
df['first'] + " " + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [20]:
df['nome_completo'] = df['first'] + " " + df['last']

In [21]:
df

   first     last                    email  nome_completo
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

USANDO MÉTODO .drop()

In [22]:
df.drop(columns = ['first', 'last'], inplace = True)
# O método drop é usado para remover as colunas 'first' e 'last' do DataFrame df. O parâmetro columns especifica quais colunas devem ser removidas,
# e o parâmetro inplace=True indica que a operação deve ser realizada no próprio DataFrame

In [23]:
df

                     email  nome_completo
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [24]:
df['nome_completo'].str.split(' ', expand = True)
# O método str.split é usado para dividir os valores da coluna 'nome_completo' em duas partes, usando o espaço como delimitador.
# O parâmetro expand=True indica que o resultado deve ser expandido em colunas separadas, resultando em um DataFrame com duas colunas,
# uma para o primeiro nome e outra para o sobrenome.

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [25]:
df

                     email  nome_completo
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [ ]:
df[['first', 'last']] = df['nome_completo'].str.split(' ', expand = True)
# O código df[['first', 'last']] = df['nome_completo'].str.split(' ', expand=True) divide a coluna 'nome_completo' em duas partes (first e last)
# O parâmetro expand = True garante que o resultado seja expandido em colunas separadas.

In [27]:
df

                     email  nome_completo  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe